# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Install dependencies'
        script:
          - npm install
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - npm run build
      - step:
          name: 'Lint'
          script:
            - npm run lint
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
